language: ruby
cache: bundler
rvm:
- 2.3.1
branches:
  only:
  - master
env:
  global:
  - GH_COMMIT_AUTHOR="Travis CI"
  - GH_COMMIT_EMAIL=mandaryyyn@gmail.com
  - secure: TbcFs11QOXMwUn9Vt9RIRtmmB1EEf0t+0xdJmq1v4kWzemrvQoar4bPfe4JVK5JRmrBIgP2m2RF2Eu/5+zlDm8CxQgV885i/FpV4x2y45jLeV41uZsNfKdruemM566+k3q4zF67g1PE1CE8HVUKRmxRz2Ogou361GdN7EA6Ajk+3tKfYcvZIpvXVfAWhDJoiopCHa/ipnLanQTpvN6WnTSpZ8xYq3RsZsNOSbbLLbePWW4oWbvqeJSPqf6dqOD3JPb9JOQLK0FcHhK5xnSx8QMJjZLlZEdPx0GgacBaJnKLdiRBfl2H4CNCqeXlpVcZVdJMqF/RlKbknIKJU3YQFegWfLKEtN0v8DOgIc2AZvMwpZx+DqRirImy+n2egxuBmYrwTHL43Wy+7JB5dKxrbduDTd2uwAVIGLhAtIywHs1eAoD/PO4VCZjvmwI3AG5S76Hfw/qJM9iLWrMDoLjsQrWxK8skwtE4hTDxyLwhNI32WmdYQx7PnYCcLEGC8GTAXz+diFs+8C/u0BfPHKAik3poilWU1DdpXJ998beId3Tgi9qhMhq22zlZMTBmNZJrN+Yun2S2JQmebLtK6p0ihXAmyXC5D/4834tyDgNf89sNEkVRgkoStI2RhK1ag78rK6moYatDIChtbKRJssDFB9sWExJmgksJRuyhSx6F8RPE=
  - secure: dFAKIfYFmjz3ioOgdlDBtc/LT7HSBcPGCEKXlNd2l0clCzxeok7FtGtb2O6IPRLvzKNUOEZbOowANRH67kmTJHGuPz1Ix/455taf0xzQPxKWxTyDuEi4c8qzqvekEUdZWPXITkXQazsd8UHfQ/mvYfxro7O/st1DpGiwKNbuN8nSgVtjeRVRu8Bruc3a9fPX0k23u5p9a1KoXm+XqocP7Q8v609Ywu0vo+7fcjKh6/VcWP/ylduonSuJFwr6GB4FYAONCYy9frE9xkJ5Sq+7wU1gnMnqdOZBnEwrCEWA4r1gljIeGvuWbInzt6QeAbjkx5yijdO2gdPdqzgrSumPsamH5t0knFzuyyny5KxH/GWqzF2aStwepRnhPW03UnIIC3O82sH2ZJ3Nhy2VW+CqN0P4Vf8DfMokjumfQ/WsE5UeoBGzumR46iZnYyM0BHF8FiyhyagkXe+n94Bc/PU6rHuaGWkg/RZ7ExJSG7tfM0KrgdfBQs3huXEsudQNMcNu/InGZHFK9JkLMALh3wnIVMpK2Wo17ZGZ7bPq6a5mf1hw4izVDYqJNdM4hU81I9aWaNSB1mx+gpEs+xLU8pELMxRA9gMxN6KKvKnUJ0fC7M7rUFw4B9ugITjw/DO4fG7WDv+p0v8UYKNqxRn2gtjDbd9vfh/i2smRMsCin6kssBk=
script:
- bundle exec rake travis:script
after_success:
- bundle exec rake travis:after_success
