language: ruby
cache: bundler
rvm:
- 2.3.1
branches:
  only:
  - master
env:
  global:
  - GH_COMMIT_AUTHOR="Mandaryn"
  - GH_COMMIT_EMAIL="mandaryyyn@gmail.com"
  - secure: E4xUMszHnlT3U0iiqZY7Y7i3dJG3ku170oVySBS5H4H4pMZbaefzDikkD79IksWx2bES+DD79+fR1jbbljk9Xlh3hiZvai+ABFOgZZxj/wyHQnBoqnc1IqjOg7P9W9cG0MKs6Kucr67wRXn64KLL+Flcm6Quhvfs7tDE8EGMe2WJ6Xj68b/cKRV9RsXAGFaNnma0lbcadZus5k8U3DoxnA89RzO5BJLD3C/dwwJEgE2QSqWnJnLrTtuHO1N/kTXrivwFF7Ju/zq931x4uo+ErFheyeqwkPQnXxuHgg58V9QtvLPNWFm6Q8VdkP+S6oeQ1BPqnR4Q+WmjoIMSxa1zwe3ZoIymWHRA6kjJ+mtZTxq1QylCXVdMluiWKOvCGEj1uEUORm3YbREh7B+1Kn6ub+KIrj2ovxdgATXGf1qN8ydRp/RZS63xQqJZSQn0zAh9h1MLfHivYtrtLdGTGF+vsq/zqpkJizW7BKPotDCZBzfQ6+Vo7H9/WZaq1AzXtsZAgVFFjLupFb4GhkYjEPB4qLINty/KQzJsQCFSHTAiirOBFqk+KY5gBeLuIQ6bWuuM96MTqWG5VMi8L4/0T//a1KBWYWgiWJm8xVK7kR3VJ41MK9Ei5sRq/NI3P2MPy2wlY6CLO5H/QFEqX5MC4nZmbtFgUpNJWpO0f2qXoJBtZDw=
script:
- bundle exec rake travis:script
after_success:
- bundle exec rake travis:after_success
