language: ruby
cache: bundler
rvm:
- 2.3.1
branches:
  only:
  - master
env:
  global:
  - GH_COMMIT_AUTHOR="Mandaryn"
  - GH_COMMIT_EMAIL="mandaryyyn@gmail.com"
  - secure: Ajj9xKF34H0pqyuazoNOak8h04/LZ0/Z7KN8kPToNRCc9K3s8ei5gEgLikY5dvnX/cfddvbZJDDvLhvwvWn2iCqmlfH3DVrSp94wNwDAejAh+7qqH5+KgCJ1+6au3umDDDAm4YXRkPrDS1ZNOB/OTlZ3ltdVrs53sUwmz07docjIbPL9241ztzqSP+lOWN6+aaQaUhv2CN82tLDPvpysItgWdhZviVdguJuE0x5WrFCfstxbNrrHRtZY8YUwYUxiGfXDnrthGe6FsIOr7YGhy2YiPJGINIhRNCFeI1loM4/Q7Gcs83rX/RV4l3eimWnIX19F3nvfiDFQycde75d1MC579NjLzRxT20BwKHyEx395J+MjwDqkhInoRP1PwvqcM/fY6BVJQSH5F2S0fewl4/ws2Ov6lc0gKg12kbG1cd98YE+ntpot++oQrlN2P9cbM3+FKHfKFVJmhfCrfbOJ+lxbFsg0x7NRIORwpyZILVTpPxuEWq3Hy23eg1cMSP3U64wpYpDgETPf2p36RjhAat7nvrclweRpQpxo8NYn+6W5ElrxbqPIawNzmskI/ID2eEiyvFn9UavXaYA/YqHX1qQYt4KcIMOGbk/KzQqaGAQW7E2r0LN5nAt1+itzpYhXoxfeXBKKecRfFC4ws1moe38lMiwqi/o4hIfla7peZ38=
script:
- bundle exec rake travis:script
after_success:
- bundle exec rake travis:after_success
