language: ruby
cache: bundler
rvm:
- 2.3.1
branches:
  only:
  - master # branch to build
env:
  global:
  - GH_COMMIT_AUTHOR="Travis CI"
  - GH_COMMIT_EMAIL=your_email@example.com
script:
- bundle exec rake travis:script
after_success:
- bundle exec rake travis:after_success
