# If you do not have OpenSSL installed, change
# the following line to use 'http://'
source 'https://rubygems.org'

# Middleman Gems
###############################
gem 'middleman'
gem 'middleman-livereload'
gem 'middleman-compass', '>= 4.0.1'
gem 'middleman-sprockets', '>= 4.0.0.rc.1'

# Middleman Extensions
###############################
# (Middleman Deploy (https://github.com/middleman-contrib/middleman-deploy/pull/87))
gem 'middleman-deploy'

# Frameworks/Library
###############################
# Bootstrap
gem 'bootstrap-sass', '>= 3.3.6'

# Font Awesome
gem 'font-awesome-sass'
